name: "build-python"
description: "Action to build a Python and poetry environment."

inputs:
  python-version:
    required: true
    description: "The python version to use"

  context-directory:
    required: true
    description: "The context directory to use"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "${{ inputs.context-directory }}/uv.lock"

    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          uv-${{ runner.os }}

    - name: Install Dependencies
      working-directory: ${{ inputs.context-directory }}
      run: uv sync
      shell: bash
      env:
        UV_CACHE_DIR: ${{ github.workspace }}/.uv-cache

    - name: Minimize uv cache
      run: uv cache prune --ci
      shell: bash
      env:
        UV_CACHE_DIR: ${{ github.workspace }}/.uv-cache

    - name: Make Check
      working-directory: ${{ inputs.context-directory }}
      run: make check
      shell: bash
